### ISSUE TITLE
[13 - log-in] Putting input in a label limits input size even if :control is true

### ISSUE THREAD

**Issue by zelark** [jacekschae/learn-re-frame-course-files#1]
`Input` is wrapped by `Label`:
```
        [:> Label {:html-for :email} "Email"
          [:> Input {:control true
```
results in following:
![screen shot 2019-03-03 at 15 58 20](https://user-images.githubusercontent.com/2854582/53695477-3d724600-3dcd-11e9-9a8d-a12e16ed532d.png)

I've checked it against 3 browsers (Chrom, Firefox, and Brave) and got the same result. So, I have no idea why it looks properly in the video (13-log-in). Probably, some magic. :)

If we don't wrap `Input`:
```
        [:> Label {:html-for :email} "Email"]
        [:> Input {:control true... ]
```
everything is rendering as expected. And I've found exactly the same markup when looked at https://app.learnreframe.com/log-in source code.

Also I checked the increments and they have this issue as well.

**Comment by jacekschae** [comment]
Could you please share your `app` function? 

The one defined in `core.cljs` at line 36

**Comment by zelark** [comment]
Sure, here we go
```
(defn app []
  (let [active-nav @(rf/subscribe [::nav.subs/active-nav])]
    [:<>
     [:> Normalize]
     [:> ThemeProvider {:theme app.theme/cheffy-theme}
      [:> Grid {:fluid false}
       [:> Row
        [:> Col
         [nav.views/nav]
         [pages active-nav]]]]]]))
```

**Comment by zelark** [comment]
Also I've run this one
https://github.com/jacekschae/learn-re-frame-course-files/blob/master/increments/14-form-group

and got the same result.

**Comment by jacekschae** [comment]
I had similar probelm before with the `Normalize` but this seems to be another issue.

They should have the same indentation.

```
[:> Label {:html-for :email} "Email"]
[:> Input {:control true... ]
```

When I do the change on my computer everything works well, despite the indentation. The only think that comes to my mind is that we might have different smooth-ui versions

and actually that explains everything ... 

screenshot from smooth-ui repo
<img width="797" alt="screen shot 2019-03-03 at 14 57 59" src="https://user-images.githubusercontent.com/31179812/53696172-d0f34900-3dc4-11e9-821c-a108f98b2d9a.png">

I belive you are running 9.0.2 and I have 9.0.1, and this is why I didn'y notice that before

Thanks again for pointing this out. Need to figure out what is the best way to correct this.

**Comment by zelark** [comment]
I haven't changed the version of smooth UI, so mine is 9.0.1.
https://github.com/jacekschae/learn-re-frame-course-files/blob/master/cheffy/package.json

**Comment by zelark** [comment]
Sorry, you're right. Checked my yarn.lock, it's 9.0.2.

**Comment by jacekschae** [comment]
I should probably lock this. Will keep this open unilt I re-upload new videos.

Thanks a ton!

**Comment by jacekschae** [comment]
Just to inform anyone who might end up here. 
Videos 13 and 14 now include information how to fix this.

**Comment by jacekschae** [comment]
Videos 13 and 14 have been re-recorded and include correct implementaion
