### ISSUE TITLE
Reitit Course

### ISSUE THREAD

**Issue by nkabir** [jacekschae/learn-re-frame-course-files#12]
Sorry for posting here. I'm excited for your new course. I just wanted to point out a typo in your image for "Cheffy API **Refernce**" (Reference)

![swagger](https://user-images.githubusercontent.com/92801/91184889-c8768880-e6b2-11ea-8e90-4ed54f1da36b.png)

**Comment by jacekschae** [comment]
Thanks for the note! Just corrected it!

https://res.cloudinary.com/schae/image/upload/f_auto,q_auto:good/v1598380009/learnreitit.com/swagger.png

I'm super excited to share it with everyone, it has been a long road to get to this point.
