### ISSUE TITLE
Some typos in https://www.learnreframe.com/

### ISSUE THREAD

**Issue by ctjhoa** [jacekschae/learn-re-frame-course-files#13]
Hi,

I notice some typos in the [website](https://www.learnreframe.com/).

1. Coeffects is listed twice

![2020-09-11-080933_1911x1600_scrot](https://user-images.githubusercontent.com/1716173/92889991-3dadc180-f406-11ea-8147-58a476e1a989.png)

2. concepst -> concepts

![2020-09-11-080913_2207x1521_scrot](https://user-images.githubusercontent.com/1716173/92889998-3f778500-f406-11ea-8e8d-d1437b1697d3.png)

**Comment by jacekschae** [comment]
Thank you! Just fixed them!
