### ISSUE TITLE
smooth-ui project abandoned

### ISSUE THREAD

**Issue by KnowledgeGarden** [jacekschae/learn-re-frame-course-files#15]
I wrote to the smooth-ui folks to ask about broken links to docs.
Greg Bergé replied that the project was abandoned. Their repo has an issue where someone recreated the docs, but where does that leave us in terms of further use of that codebase?

**Comment by jacekschae** [comment]
Hi Jack,

Thanks for reaching out.

I chose smooth-ui mainly to decrease the amount of html I would have to write if I would not use it. In retrospect I regret that and hope to address this. 

When it comes to the code baee I believe it’s still very relevant. The aim of the course is not to teach you how to use smooth-ui but re-frame and all of the concepts are still 100% applicable.

Hope that helps,

Jacek

**Comment by KnowledgeGarden** [comment]
Hi Jacek,

Happy to hear from you.

That does, indeed help, as do the lectures around this code.
What has bothered me is an apparent inability to wire a re-frame app to datalog and datomic; that caused me to start looking around.

Thanks
Jack

**Comment by jacekschae** [comment]
Did you take a look at https://github.com/denistakeda/re-posh also check out the Secret Interceptors section from re-frame docs -- http://day8.github.io/re-frame/Coeffects/#secret-interceptors

Hope that helps with DataScript integration.

**Comment by jacekschae** [comment]
@KnowledgeGarden could we close this one?

**Comment by KnowledgeGarden** [comment]
Yes!
