### ISSUE TITLE
Increments contains now node_modules directory

### ISSUE THREAD

**Issue by PrestanceDesign** [jacekschae/learn-re-frame-course-files#2]
Hi Jacek,

Since the *25-recipes-list* increments, commits now contains *node_modules* directory despite the 
.gitignore so it slowdown drastically my Emacs/Magit workflow.
Do you aware of that or it isn't wanted ?

Best regards.
Mike

**Comment by jacekschae** [comment]
Hi there, thanks for pointing this out. I wasn't aware that the `.gitignore` was not ignoring. Seems like they were cached. 

I just did a clean-up and it should be good.
