### ISSUE TITLE
Having problems running complete version of project locally

### ISSUE THREAD

**Issue by NguyenDa18** [jacekschae/learn-re-frame-course-files#5]
Starting out with reagent and reframe (Clojure novice) and want to learn from course but having errors running locally -nothing is even rendered because of these errors.

[](url)
<img width="952" alt="cheffy_error" src="https://user-images.githubusercontent.com/14105469/72477418-52b55080-37a4-11ea-8323-136778058427.png">

**Comment by jacekschae** [comment]
Hi @NguyenDa18 
Thanks for letting me know about this problem. I just traced it and it looks like there is a problem with `day8.re-frame/tracing` package. You need to open the `shadow-cljs.edn` and then updated ```:dependencies```: 
from:
`[day8.re-frame/tracing "0.5.1"]`
to (mind the minor version number):
`[day8.re-frame/tracing "0.5.3"]`

I just updated the repo and fixed this and one more issue with spec - for more details see below:
If you don't pull the latest there is also one more problem with spec - I assumed that when you get to compete you went through all the steps of building the app and that the `:auth` is always a `map - {} `. That said, when you just clone the repo and open the complete app `:auth` is `nil` and therefore it doesn't work. I have also corrected that so it should be all good when you clone the latests.

One more time thanks for reporting this and letting me know about this problem. 

I'm traveling right now therefore, slow response time.

If you would have any further questions or anything would be not clear please let me know. 

If you believe this solves the problem please close the issue after verifying.

**Comment by NguyenDa18** [comment]
Thank you so much for the quick fix! Working locally for me now and am excited to start digging in.
