### ISSUE TITLE
Uncaught error with signing up user locally

### ISSUE THREAD

**Issue by NguyenDa18** [jacekschae/learn-re-frame-course-files#6]
Getting error with sign up of new test user:
First name: "Henry"
Last name: "Kissel"
Email: "kissel@fakeamail.com"
Password: "#Kisseltalks2020!"

- Happening at function check-and-throw. Perhaps an enhancement for the project is to output errors as UI alerts rather than in console.
Looks like invalid substring is being found in the input, as seen in the error details mentioning contains? function failing with the input.

Screenshots:
<img width="1580" alt="Screen Shot 2020-01-21 at 4 03 41 PM" src="https://user-images.githubusercontent.com/14105469/72854369-01580600-3c69-11ea-8b81-58c4786514da.png">
<img width="1512" alt="Screen Shot 2020-01-21 at 4 03 47 PM" src="https://user-images.githubusercontent.com/14105469/72854370-01580600-3c69-11ea-8e17-de15478bbfe0.png">

**Comment by jacekschae** [comment]
Hi again,

Thanks for this again. Just fixed it. Will have to re-record some of the videos - thanks for making the course better!

Just fixed the signup event - let me know if this works for you.
https://github.com/jacekschae/learn-re-frame-course-files/blob/ec2b3e10976ecf41b96236741e16080849d81ef3/increments/complete/src/app/auth/events.cljs#L41

Thanks Jacek

**Comment by NguyenDa18** [comment]
No problem! Thanks for the fix again and my attempt of signing up again was successful!
