### ISSUE TITLE
NPM Dependency issue 

### ISSUE THREAD

**Issue by themustafabasit** [jacekschae/learn-re-frame-course-files#9]
**can you please tell me which dependency should I update**

npm WARN **deprecated core-js@1.2.7: core-js@<3** is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

npm ERR! Unexpected end of JSON input while parsing near '...5LBAUd78/t/8Xl+oJc\nh'

**Log File**
0 info it worked if it ends with ok 
...
...
...
480 silly resolveWithNewModule react-dom@16.13.1 checking installable status
481 silly pacote range manifest for create-react-class@^15.6.3 fetched in 6ms
482 silly resolveWithNewModule create-react-class@15.6.3 checking installable status
483 silly pacote version manifest for @smooth-ui/core-sc@9.0.2 fetched in 7ms
484 silly resolveWithNewModule @smooth-ui/core-sc@9.0.2 checking installable status
485 silly pacote range manifest for styled-components@^4.1.2 fetched in 7ms
486 silly resolveWithNewModule styled-components@4.4.1 checking installable status
487 silly pacote range manifest for styled-icons@^10.6.0 fetched in 7ms
488 silly resolveWithNewModule styled-icons@10.6.0 checking installable status
489 http fetch GET 304 https://registry.npmjs.org/react 124ms (from cache)
490 silly fetchPackageMetaData error for react@^16.13.1 Unexpected end of JSON input while parsing near '...5LBAUd78/t/8Xl+oJc\nh'
491 timing stage:rollbackFailedOptional Completed in 0ms
492 timing stage:runTopLevelLifecycles Completed in 14440ms
493 silly saveTree Cheffy@0.0.1
493 silly saveTree +-- @smooth-ui/core-sc@9.0.2
493 silly saveTree +-- create-react-class@15.6.3
493 silly saveTree +-- react-dom@16.13.1
493 silly saveTree +-- styled-components@4.4.1
493 silly saveTree `-- styled-icons@10.6.0
494 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...5LBAUd78/t/8Xl+oJc\nh'
494 verbose stack     at JSON.parse (<anonymous>)
494 verbose stack     at parseJson (/home/mustafa-basit/node-v12.18.1-linux-x64/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7>
494 verbose stack     at /home/mustafa-basit/node-v12.18.1-linux-x64/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
494 verbose stack     at runMicrotasks (<anonymous>)
494 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
495 verbose cwd /home/mustafa-basit/Documents/Git@MustafaBasit/Clojurescript/cheffy
496 verbose Linux 5.3.0-61-generic
497 verbose argv "/home/mustafa-basit/node-v12.18.1-linux-x64/bin/node" "/home/mustafa-basit/node-v12.18.1-linux-x64/bin/npm" "install" "--force"
498 verbose node v12.18.1
499 verbose npm  v6.14.5
500 error Unexpected end of JSON input while parsing near '...5LBAUd78/t/8Xl+oJc\nh'
501 verbose exit [ 1, true ]

**Comment by jacekschae** [comment]
Hi there, sorry to see that you have some problems. 

Cider went through quite a bit of changes at one point and this might be the problem:

Please update your shadow-cljs.edn as follows:

`shadow-cljs.edn`

```clojure
{:source-paths ["src"]

 :dependencies [[proto-repl "0.3.1"]
                [binaryage/devtools "0.9.10"]
                [reagent "0.8.1"]
                [re-frame "0.10.6"]
                [day8.re-frame/re-frame-10x "0.3.6-react16"]
                [bidi "2.1.5"]
                [kibu/pushy "0.3.8"]
                [com.andrewmcveigh/cljs-time "0.5.2"]]

 :nrepl        {:port 3333}

 :fs-watch {:hawk false}
 
 :builds {:app {:target :browser
                :output-dir "public/js"
                :asset-path "/js"

                :modules {:main {:init-fn app.core/init}}

                :compiler-options {:closure-defines {re-frame.trace/trace-enabled? true
                                                     day8.re-frame.tracing/trace-enabled? true}}

                :devtools {:http-root   "public"
                           :http-port   3000
                           :preloads    [day8.re-frame-10x.preload]}}}}
```

**Comment by themustafabasit** [comment]
**shadow-cljs - dependencies updated**
Thank you boss 🤗
